"""add address table

Revision ID: 014ccfc660cc
Revises: 42a112b2e157
Create Date: 2026-05-08 18:27:46.872734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014ccfc660cc'
down_revision: Union[str, Sequence[str], None] = '42a112b2e157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id_address', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_address')
    )
    op.create_index(op.f('ix_address_id_address'), 'address', ['id_address'], unique=False)
    op.add_column('contact', sa.Column('id_address', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact', 'address', ['id_address'], ['id_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'id_address')
    op.drop_index(op.f('ix_address_id_address'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
