"""add about specialty and genre to contact

Revision ID: 1314606eb26e
Revises: 3a16a65f7775
Create Date: 2026-04-17 14:21:07.469380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1314606eb26e'
down_revision: Union[str, Sequence[str], None] = '3a16a65f7775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('about', sa.String(length=250), nullable=True))
    op.add_column('contact', sa.Column('specialty', sa.String(length=50), nullable=True))
    op.add_column('contact', sa.Column('genre', sa.Integer(), nullable=True))
    op.drop_column('cycle', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('contact', 'genre')
    op.drop_column('contact', 'specialty')
    op.drop_column('contact', 'about')
    # ### end Alembic commands ###
