"""add position to cycle

Revision ID: 2e75adf9bd8a
Revises: c66858b1ee0c
Create Date: 2026-04-07 18:11:25.999248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e75adf9bd8a'
down_revision: Union[str, Sequence[str], None] = 'c66858b1ee0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle', sa.Column('position', sa.Integer(), nullable=True))
    op.drop_column('cycle', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cycle', 'position')
    # ### end Alembic commands ###
