"""add last_period_date and regularity to clinical_history

Revision ID: 3a16a65f7775
Revises: 859670558dcd
Create Date: 2026-04-08 19:21:49.832113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a16a65f7775'
down_revision: Union[str, Sequence[str], None] = '859670558dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_history', sa.Column('last_period_date', sa.Date(), nullable=True))
    op.add_column('clinical_history', sa.Column('regularity', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_history', 'regularity')
    op.drop_column('clinical_history', 'last_period_date')
    # ### end Alembic commands ###
