"""remove unique constraint from contact email and phone

Revision ID: 42a112b2e157
Revises: a74d66337eb2
Create Date: 2026-05-03 21:02:41.620226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a112b2e157'
down_revision: Union[str, Sequence[str], None] = 'a74d66337eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contact_email_key'), 'contact', type_='unique')
    op.drop_constraint(op.f('contact_phone_number_key'), 'contact', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('contact_phone_number_key'), 'contact', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('contact_email_key'), 'contact', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
