"""remove position from cycle

Revision ID: 859670558dcd
Revises: 2e75adf9bd8a
Create Date: 2026-04-07 19:18:35.098126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859670558dcd'
down_revision: Union[str, Sequence[str], None] = '2e75adf9bd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cycle', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
