"""update reminder model

Revision ID: a74d66337eb2
Revises: b15d89b59cb6
Create Date: 2026-04-25 13:44:45.116016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a74d66337eb2'
down_revision: Union[str, Sequence[str], None] = 'b15d89b59cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('reminder', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('reminder', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('reminder', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('reminder', sa.Column('dosage', sa.String(length=100), nullable=True))
    op.add_column('reminder', sa.Column('after_meal', sa.Boolean(), nullable=True))
    op.add_column('reminder', sa.Column('status', sa.Integer(), nullable=False))
    op.alter_column('reminder', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='CASE WHEN type = \'medication\' THEN true WHEN type = \'appointment\' THEN false ELSE NULL END')
    op.drop_column('reminder', 'repeats')
    op.drop_column('reminder', 'is_completed')
    op.drop_column('reminder', 'time')
    op.drop_column('reminder', 'priority')
    op.drop_column('reminder', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('reminder', sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('reminder', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('reminder', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('reminder', sa.Column('repeats', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('reminder', 'type',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('reminder', 'status')
    op.drop_column('reminder', 'after_meal')
    op.drop_column('reminder', 'dosage')
    op.drop_column('reminder', 'end_time')
    op.drop_column('reminder', 'end_date')
    op.drop_column('reminder', 'start_time')
    op.drop_column('reminder', 'start_date')
    # ### end Alembic commands ###
