"""add last_verification_sent to user

Revision ID: b15d89b59cb6
Revises: 9223ab90602e
Create Date: 2026-04-22 11:55:15.415643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15d89b59cb6'
down_revision: Union[str, Sequence[str], None] = '9223ab90602e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_verification_sent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_sent')
    # ### end Alembic commands ###
