"""make miscarriages_abortions optional

Revision ID: c66858b1ee0c
Revises: 47e72d6c6ce5
Create Date: 2026-04-07 11:59:38.585009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66858b1ee0c'
down_revision: Union[str, Sequence[str], None] = '47e72d6c6ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
