"""replace start and end time with day_time in reminder

Revision ID: de31272eeaf2
Revises: 42a112b2e157
Create Date: 2026-05-08 17:47:22.411752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de31272eeaf2'
down_revision: Union[str, Sequence[str], None] = '42a112b2e157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('day_time', sa.Time(), nullable=True))
    op.drop_column('reminder', 'start_time')
    op.drop_column('reminder', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('reminder', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('reminder', 'day_time')
    # ### end Alembic commands ###
